### ISSUE TITLE
Name change: xrootdfs -> xrootdpyfs

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/xrootdpyfs#65]
To avoid conflicts with FUSE xrootdfs it's been suggested to change the name to xrootdpyfs

- [x] GitHub repo: Transfer to new name.
- [x] PyPI: Remove existing package ASAP and register new package name.
- [x] setup.py
- [x] git move xrootdfs/ -> xrootdpyfs/
- [x] Update source (i.e. imports)
- [x] Update source code headers.
- [x] Update documentation.

**Comment by otron** [comment]
@lnielsen I don't have owner-level access to the `xrootdfs` package on PyPi (it's owned by "inveniosoftware" and "lnielsen").
Could you take care of the removal of `xrootdfs` and register `xrootdpyfs`?

**Comment by otron** [comment]
I don't have access to rename the repository either.
@lnielsen the last two items on the check list are up to you. :)

**Comment by kiryx** [comment]
* Title underline should be two dashes longer here: https://github.com/inveniosoftware/xrootdfs/pull/66/files#diff-dc8cf0cd192ecdec444dc298e9030bb3R105
* Some leftovers in non-code files when you run ``git grep xrootdfs`` from root dir of repo (e.g ``.coveragerc``, ``.travis.yml``, ``Dockerfile`` or ``README.rst`` etc.)
