### ISSUE TITLE
Register package `xrootdpyfs` on PyPi & delete `xrootdfs`

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdpyfs#68]
* Related to the GRAND RENAMING ( #65 ).

* Deleting the `xrootdfs` package (https://pypi.python.org/pypi/xrootdfs/0.1.0) has to be done by one of its owners (_cough_ @lnielsen _cough_)

* The organization account should probably register the new package name.

* Needs to be done _before_ #66 is merged in.

**Comment by lnielsen** [comment]
I can't be done after merging #66?

**Comment by otron** [comment]
Sorry, I meant that registering the new package name needs to be done
before merging #66. Deleting the old one shouldn't be done until after #66
has been merged.

**Comment by lnielsen** [comment]
https://pypi.python.org/pypi/xrootdpyfs
