### ISSUE TITLE
Unable to install from pip

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdpyfs#69]
```
$ pip install xrootdpyfs
> Could not find a version that satisfies the requirement pyxrootd (from xrootdpyfs) (from versions: )
> No matching distribution found for pyxrootd (from xrootdpyfs)
```

There's no package called "pyxrootd" on pip. Neither do we ever actually reference any such package in the source.
The [`pyxrootd`](http://xrootd.org/doc/python/xrootd-python-0.1.0/) "package" installs as `xrootd`. But it's not available on pip.

**Comment by otron** [comment]
We should probably just remove the requirement from `setup.py`, no?

**Comment by lnielsen** [comment]
We're dependent on xrootd-python and it installs itself as ``pyxrootd``: https://github.com/xrootd/xrootd/blob/master/bindings/python/setup_pypi.py#L44

**Comment by lnielsen** [comment]
I think we need to check how to make the packages available on pypi

**Comment by otron** [comment]
Your suggestion is a lot more sensible than mine.

**Comment by otron** [comment]
Here's how to install the prerequisites on OSX:
1. Install xrootd via Homebrew
  - `brew install xrootd`
2. Install pyxrootd by cloning the repo
    a. `$ git clone git://github.com/xrootd/xrootd-python.git && cd xrootd-python`
    b. `$ export XRD_INCDIR='/usr/local/Cellar/xrootd/4.1.1/include/xrootd'
    c. `$ export XRD_LIBDIR='/usr/local/Cellar/xrootd/4.1.1/lib'
    d. `$ python setup.py install --user`
3. Install xrootdpyfs via pip
   - `pip install xrootdpyfs`
