### ISSUE TITLE
What is the reason for constraining pyfs to <2.0.0?

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/xrootdpyfs#82]
Should we support pyfs 2.0? https://github.com/PyFilesystem/pyfilesystem2
It looks much more active compared to pyfs 0.5.x branch:
 https://github.com/PyFilesystem/pyfilesystem/commits/master

**Comment by lnielsen** [comment]
Incompatibility:-)

**Comment by krzysztof** [comment]
Is this something we could fix here or does it involve the C library changes?
If not we can probably close this issue.

**Comment by lnielsen** [comment]
Eventually, yes we should support fs 2.0 and it touches only our python code. But FS 2.0 has some large API changes, and I think it will take some time to get xrootdpyfs properly updated and not least tested for all the edge cases.
